"use client";

import { LegalShell, H, P, Ul, Li, B, A } from "@/components/legal/shell";

export default function PrivacyPage() {
  return (
    <LegalShell title="Privacy Policy" updated="17 April 2026">
      <P>
        DevAstroAI (&quot;we&quot;, &quot;our&quot;) is operated by DevAstro Labs, Hyderabad,
        India. This policy explains what data we collect, why we collect it, and
        what your rights are. It applies to users of the DevAstroAI website,
        consumer app, and pro astrologer workspace.
      </P>

      <H>1. Information we collect</H>
      <P>
        <B>Account data:</B> name, email, chosen role (consumer or astrologer),
        and hashed password (managed by Supabase Auth — we never store raw
        passwords).
      </P>
      <P>
        <B>Birth data you enter:</B> name, birth date, birth time, birth place,
        latitude, longitude, and timezone of yourself or clients you add. This
        data is required to compute KP charts.
      </P>
      <P>
        <B>Practice data (pro tier):</B> client profiles, session notes,
        predictions, follow-ups, and chart exports you create while using the
        tool.
      </P>
      <P>
        <B>Usage data:</B> anonymised event data (pages viewed, features used)
        via PostHog; crash reports via Sentry. You can opt out via the Settings
        page.
      </P>

      <H>2. How we use your data</H>
      <Ul>
        <Li>To compute astrological charts and AI interpretations on your request</Li>
        <Li>To store your workspace so you can return to it across devices</Li>
        <Li>To send transactional emails (sign-up confirmation, follow-up reminders, session summaries)</Li>
        <Li>To improve the product (aggregated, anonymised usage only)</Li>
      </Ul>
      <P>
        We do not sell your data. We do not share client data between astrologer
        accounts. Multi-tenant isolation is enforced at the database (Postgres
        Row-Level Security) and application level.
      </P>

      <H>3. AI processing</H>
      <P>
        Chart interpretations are generated by Anthropic&apos;s Claude API. The
        prompt we send includes your chart data, the question you asked, and
        the KP context. Anthropic does not train on API traffic. Nothing you
        enter is used to improve third-party models.
      </P>

      <H>4. Third-party services</H>
      <Ul>
        <Li><B>Supabase</B> — auth and database</Li>
        <Li><B>Anthropic</B> — AI interpretation (Claude models)</Li>
        <Li><B>Resend</B> — transactional email delivery</Li>
        <Li><B>PostHog</B> — product analytics (anonymised)</Li>
        <Li><B>Sentry</B> — error monitoring</Li>
        <Li><B>Stripe</B> (future) — payments; we never see your full card number</Li>
      </Ul>

      <H>5. Data retention</H>
      <P>
        Active account data is retained for as long as your account exists. If
        you delete your account, we wipe your workspace within 30 days.
        Anonymised aggregate analytics may be retained longer.
      </P>

      <H>6. Your rights (GDPR / DPDP)</H>
      <Ul>
        <Li>Request a copy of your data (export)</Li>
        <Li>Correct inaccurate data</Li>
        <Li>Delete your data (&quot;right to be forgotten&quot;)</Li>
        <Li>Object to specific processing</Li>
      </Ul>
      <P>
        Email <A href="mailto:privacy@devastro.ai">privacy@devastro.ai</A> and
        we&apos;ll respond within 14 days.
      </P>

      <H>7. Children</H>
      <P>
        DevAstroAI is not intended for users under 13. We do not knowingly
        collect data from children. If you believe we have, contact us and we
        will delete it.
      </P>

      <H>8. Changes</H>
      <P>
        If we materially change this policy, we&apos;ll email registered users
        and update the &quot;Last updated&quot; date at the top.
      </P>

      <H>9. Contact</H>
      <P>
        DevAstro Labs, Hyderabad 500032, India.
        <br />
        <A href="mailto:support@devastro.ai">support@devastro.ai</A>
      </P>
    </LegalShell>
  );
}
