"""/clients — CRUD for the astrologer's client roster (Phase 2 Slice 2).

LOGGING NOTE (2026-06-02 hotfix): Wrapped create_client in explicit
try/except with logger.exception to surface the actual stack trace in
Railway logs. If you see 500s on POST /clients, check Railway logs for
"create_client_failed" — the stack trace will pinpoint the cause.


This is the CRM data layer that the new /app home (CRM-first) reads
from and writes to. Each row in `clients` is one real-world person the
astrologer is consulting for.

Design notes (per master plan 2026-06-02):
  - This endpoint creates ONLY the client row. Chart computation +
    initial chart_session creation are SEPARATE endpoints
    (/astrologer/workspace + /chart-sessions). The frontend
    orchestrates the 3-call flow when a new client is added with
    birth details.
  - Rationale: each REST resource stays independent. A failed chart
    computation doesn't leave an orphan client; the user can retry.
  - portal_slug is auto-generated by the DB (gen_random_uuid()
    default) — astrologers get a unique public client URL the moment
    the client row exists.
  - Ownership filter: every endpoint scopes by
    astrologer_id == current_astrologer.id. 404 (not 403) on
    cross-astrologer access to avoid leaking row existence.

Endpoints:
  GET    /clients              — list current astrologer's clients
  POST   /clients              — create a new client
  GET    /clients/{id}         — read one
  PATCH  /clients/{id}         — partial update
  DELETE /clients/{id}         — delete (cascades to chart_sessions)
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Optional
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, ConfigDict, Field
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth import CurrentAstrologer
from app.db import get_db
from app.db.models import ChartSession, Client, ClientNote

router = APIRouter()
_log = logging.getLogger("kp_astro.clients")


# ─── Schemas ──────────────────────────────────────────────────────────


class ClientBase(BaseModel):
    """Shared input fields for create + update.

    All optional on update (PATCH semantics). `name` required on create.
    Birth fields all optional — astrologer might add a client with just
    a name + phone before they've collected birth data.
    """

    name: Optional[str] = Field(default=None, max_length=200)
    phone: Optional[str] = Field(default=None, max_length=20)
    email: Optional[str] = Field(default=None, max_length=320)
    gender: Optional[str] = Field(default=None, max_length=10)

    birth_date: Optional[str] = Field(default=None, max_length=10)
    birth_time: Optional[str] = Field(default=None, max_length=8)
    birth_place_name: Optional[str] = Field(default=None, max_length=500)
    birth_latitude: Optional[float] = None
    birth_longitude: Optional[float] = None
    birth_timezone_offset: Optional[float] = None

    matching_opt_in: Optional[bool] = None
    summary: Optional[str] = None


class ClientCreate(ClientBase):
    """POST body — name is required."""

    name: str = Field(..., max_length=200)


class ClientUpdate(ClientBase):
    """PATCH body — every field optional, only changed fields applied."""

    pass


class ClientPublic(ClientBase):
    """Response shape returned to the astrologer (includes server-set
    fields + computed counts).

    NOTE: This is the ASTROLOGER's view of a client. The PUBLIC client
    portal page (`/c/<portal_slug>`) returns a different shape — much
    less info, no astrologer-private fields like summary or
    matching_opt_in. That's a separate endpoint shipped in Phase 3.
    """

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    astrologer_id: UUID
    name: str
    portal_slug: UUID

    # Convenience counts. Useful for the CRM roster ("Harini · 12 sessions, 3 notes")
    # without an extra round-trip per row.
    chart_session_count: int = 0
    note_count: int = 0
    last_session_at: Optional[datetime] = None

    created_at: datetime
    updated_at: datetime


class ClientList(BaseModel):
    """List response wrapper.

    Pagination + total kept as wrapper so we can add cursor pagination
    later without a breaking change. For v1, we return everything in
    one shot (most astrologers will have <500 clients; offset/limit
    is enough).
    """

    items: list[ClientPublic]
    total: int


# ─── Helpers ──────────────────────────────────────────────────────────


async def _get_owned_or_404(
    client_id: UUID,
    astrologer: CurrentAstrologer,
    db: AsyncSession,
) -> Client:
    """Look up a client and verify the current astrologer owns it.

    Raises 404 if missing OR owned by someone else (don't leak
    existence). Same pattern as chart_sessions router.
    """
    stmt = select(Client).where(
        Client.id == client_id,
        Client.astrologer_id == astrologer.id,
    )
    result = await db.execute(stmt)
    row = result.scalar_one_or_none()
    if row is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"error": "client_not_found"},
        )
    return row


def _client_to_public(
    row: Client,
    chart_session_count: int = 0,
    note_count: int = 0,
    last_session_at: Optional[datetime] = None,
) -> ClientPublic:
    """Build ClientPublic explicitly from a Client SQLAlchemy row.

    2026-06-02 hotfix: was using ClientPublic.model_validate(row) which
    uses Pydantic's from_attributes=True. That triggered 500 errors on
    POST /clients because Pydantic was traversing SQLAlchemy attributes
    in a way that conflicted with our `lazy="raise"` relationship
    setting (any incidental access of row.chart_sessions or row.notes
    raises InvalidRequestError on a freshly-flushed row whose
    relationships haven't been eager-loaded).

    Explicit field mapping avoids the issue entirely — we only read
    scalar columns, never relationships.
    """
    return ClientPublic(
        id=row.id,
        astrologer_id=row.astrologer_id,
        name=row.name,
        phone=row.phone,
        email=row.email,
        gender=row.gender,
        birth_date=row.birth_date,
        birth_time=row.birth_time,
        birth_place_name=row.birth_place_name,
        birth_latitude=row.birth_latitude,
        birth_longitude=row.birth_longitude,
        birth_timezone_offset=row.birth_timezone_offset,
        matching_opt_in=row.matching_opt_in,
        portal_slug=row.portal_slug,
        summary=row.summary,
        chart_session_count=chart_session_count,
        note_count=note_count,
        last_session_at=last_session_at,
        created_at=row.created_at,
        updated_at=row.updated_at,
    )


async def _attach_counts(
    rows: list[Client],
    db: AsyncSession,
) -> list[ClientPublic]:
    """Bulk-compute chart_session + note counts for a list of clients.

    Two queries (one per related table) regardless of list size, vs
    N+1 queries if we did this naively per row.
    """
    if not rows:
        return []

    client_ids = [r.id for r in rows]

    # Chart session counts + most-recent updated_at per client
    sess_stmt = (
        select(
            ChartSession.client_id,
            func.count(ChartSession.id).label("cnt"),
            func.max(ChartSession.updated_at).label("last_at"),
        )
        .where(ChartSession.client_id.in_(client_ids))
        .group_by(ChartSession.client_id)
    )
    sess_rows = (await db.execute(sess_stmt)).all()
    sess_map: dict[UUID, tuple[int, datetime]] = {
        r.client_id: (r.cnt, r.last_at) for r in sess_rows
    }

    # Note counts per client
    note_stmt = (
        select(
            ClientNote.client_id,
            func.count(ClientNote.id).label("cnt"),
        )
        .where(ClientNote.client_id.in_(client_ids))
        .group_by(ClientNote.client_id)
    )
    note_rows = (await db.execute(note_stmt)).all()
    note_map: dict[UUID, int] = {r.client_id: r.cnt for r in note_rows}

    out: list[ClientPublic] = []
    for r in rows:
        sess_cnt, last_at = sess_map.get(r.id, (0, None))
        out.append(
            _client_to_public(
                r,
                chart_session_count=sess_cnt,
                note_count=note_map.get(r.id, 0),
                last_session_at=last_at,
            )
        )
    return out


# ─── Routes ───────────────────────────────────────────────────────────


@router.get("", response_model=ClientList)
async def list_clients(
    astrologer: CurrentAstrologer,
    db: AsyncSession = Depends(get_db),
) -> ClientList:
    """List the current astrologer's clients, most-recently-touched first.

    Sort key: max(client.updated_at, last chart_session updated_at).
    Approximation for v1: just client.updated_at. We can refine to
    LAST_SESSION_AT-DESC if astrologers say "I want to see who I
    consulted with most recently" instead of "who I edited most
    recently in the CRM."
    """
    stmt = (
        select(Client)
        .where(Client.astrologer_id == astrologer.id)
        .order_by(Client.updated_at.desc())
    )
    result = await db.execute(stmt)
    rows = list(result.scalars().all())
    enriched = await _attach_counts(rows, db)
    return ClientList(items=enriched, total=len(enriched))


@router.post(
    "",
    response_model=ClientPublic,
    status_code=status.HTTP_201_CREATED,
)
async def create_client(
    payload: ClientCreate,
    astrologer: CurrentAstrologer,
    db: AsyncSession = Depends(get_db),
) -> ClientPublic:
    """Create a new client owned by the current astrologer.

    Does NOT compute the chart — that's a separate flow. Frontend
    typically does:
      1. POST /clients with name + birth details → creates client row
      2. POST /astrologer/workspace with birth details → computes chart
      3. POST /chart-sessions with client_id + workspace_data → persists
    See the CRM Add Client modal in Slice 3 for the orchestration.
    """
    # Detailed error catching: 500s on this endpoint were misleadingly
    # surfacing as CORS errors in the browser (fixed in 18fb86a). Now
    # they surface correctly, but we still don't see the stack trace
    # without proper logging. Catch + log + raise a 500 with the
    # exception class name so the frontend can show something useful
    # while we debug.
    try:
        row = Client(
            astrologer_id=astrologer.id,
            **payload.model_dump(exclude_unset=True),
        )
        db.add(row)
        await db.flush()  # populate id + portal_slug + created_at
        # Newly created → zero sessions / notes. Use explicit
        # constructor (not model_validate) — see _client_to_public
        # docstring for why.
        return _client_to_public(row, chart_session_count=0, note_count=0)
    except HTTPException:
        raise
    except Exception as e:
        # Log the FULL stack trace to Railway logs so we can debug.
        _log.exception(
            "create_client_failed astrologer_id=%s payload_keys=%s",
            astrologer.id,
            list(payload.model_dump(exclude_unset=True).keys()),
        )
        # Rollback so the session can be reused for the next request.
        try:
            await db.rollback()
        except Exception:
            pass
        # Surface the exception class name + first 200 chars of msg in
        # the response so the frontend can show something specific.
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "error": "create_client_failed",
                "exception_type": type(e).__name__,
                "exception_message": str(e)[:200],
            },
        )


@router.get("/{client_id}", response_model=ClientPublic)
async def get_client(
    client_id: UUID,
    astrologer: CurrentAstrologer,
    db: AsyncSession = Depends(get_db),
) -> ClientPublic:
    """Read one client by id (must be owned by current astrologer)."""
    row = await _get_owned_or_404(client_id, astrologer, db)
    enriched = await _attach_counts([row], db)
    return enriched[0]


@router.patch("/{client_id}", response_model=ClientPublic)
async def update_client(
    client_id: UUID,
    payload: ClientUpdate,
    astrologer: CurrentAstrologer,
    db: AsyncSession = Depends(get_db),
) -> ClientPublic:
    """Update one or more fields. Unset fields are not touched.

    NOTE: birth fields are mutable here. If the astrologer rectifies
    the birth time, this updates them. BUT the chart_sessions rows
    have their own birth-field snapshots (see ChartSession model
    docstring) — those don't auto-update. That's by design: each
    chart_session captures the input used when it was created, so
    rectification creates a new chart_session, not mutates old ones.
    The frontend (in Slice 3+) presents rectification as
    "Recompute chart" → which POSTs a new /chart-sessions row, not
    a PATCH of an existing one.
    """
    row = await _get_owned_or_404(client_id, astrologer, db)
    changes = payload.model_dump(exclude_unset=True)
    for field, value in changes.items():
        setattr(row, field, value)
    await db.flush()
    enriched = await _attach_counts([row], db)
    return enriched[0]


@router.delete("/{client_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_client(
    client_id: UUID,
    astrologer: CurrentAstrologer,
    db: AsyncSession = Depends(get_db),
) -> None:
    """Delete a client. CASCADES to chart_sessions + client_notes via
    the FK ON DELETE CASCADE we set up in the initial migration.

    Idempotent — 404 if it doesn't exist (or isn't yours).

    WARNING: This is destructive. The frontend should confirm before
    calling (\"Delete client + N chart sessions + M notes — are you
    sure?\"). No soft-delete in v1; we'll add a `deleted_at` column
    + tombstone behavior if astrologers ask for "undelete."
    """
    row = await _get_owned_or_404(client_id, astrologer, db)
    await db.delete(row)
