"""/clients — CRUD for the astrologer's client roster (Phase 2 Slice 2).

LOGGING NOTE (2026-06-02 hotfix): Wrapped create_client in explicit
try/except with logger.exception to surface the actual stack trace in
Railway logs. If you see 500s on POST /clients, check Railway logs for
"create_client_failed" — the stack trace will pinpoint the cause.


This is the CRM data layer that the new /app home (CRM-first) reads
from and writes to. Each row in `clients` is one real-world person the
astrologer is consulting for.

Design notes (per master plan 2026-06-02):
  - This endpoint creates ONLY the client row. Chart computation +
    initial chart_session creation are SEPARATE endpoints
    (/astrologer/workspace + /chart-sessions). The frontend
    orchestrates the 3-call flow when a new client is added with
    birth details.
  - Rationale: each REST resource stays independent. A failed chart
    computation doesn't leave an orphan client; the user can retry.
  - portal_slug is auto-generated by the DB (gen_random_uuid()
    default) — astrologers get a unique public client URL the moment
    the client row exists.
  - Ownership filter: every endpoint scopes by
    astrologer_id == current_astrologer.id. 404 (not 403) on
    cross-astrologer access to avoid leaking row existence.

Endpoints:
  GET    /clients              — list current astrologer's clients
  POST   /clients              — create a new client
  GET    /clients/{id}         — read one
  PATCH  /clients/{id}         — partial update
  DELETE /clients/{id}         — delete (cascades to chart_sessions)
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any, Optional
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, ConfigDict, Field
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth import CurrentAstrologer
from app.db import get_db
from app.db.models import ChartSession, Client, ClientNote

router = APIRouter()
_log = logging.getLogger("kp_astro.clients")


# ─── Schemas ──────────────────────────────────────────────────────────


class ClientBase(BaseModel):
    """Shared input fields for create + update.

    All optional on update (PATCH semantics). `name` required on create.
    Birth fields all optional — astrologer might add a client with just
    a name + phone before they've collected birth data.
    """

    name: Optional[str] = Field(default=None, max_length=200)
    phone: Optional[str] = Field(default=None, max_length=20)
    email: Optional[str] = Field(default=None, max_length=320)
    gender: Optional[str] = Field(default=None, max_length=10)

    birth_date: Optional[str] = Field(default=None, max_length=10)
    birth_time: Optional[str] = Field(default=None, max_length=8)
    birth_place_name: Optional[str] = Field(default=None, max_length=500)
    birth_latitude: Optional[float] = None
    birth_longitude: Optional[float] = None
    birth_timezone_offset: Optional[float] = None

    matching_opt_in: Optional[bool] = None
    summary: Optional[str] = None

    # Portal controls (added 2026-06-02, migration 0003 — S5, C10).
    # PATCH-friendly: each toggle independently optional.
    portal_enabled: Optional[bool] = None
    portal_visibility: Optional[dict] = None


class ClientCreate(ClientBase):
    """POST body — name is required."""

    name: str = Field(..., max_length=200)


class ClientUpdate(ClientBase):
    """PATCH body — every field optional, only changed fields applied."""

    pass


class ClientPublic(ClientBase):
    """Response shape returned to the astrologer (includes server-set
    fields + computed counts).

    NOTE: This is the ASTROLOGER's view of a client. The PUBLIC client
    portal page (`/c/<portal_slug>`) returns a different shape — much
    less info, no astrologer-private fields like summary or
    matching_opt_in. That's a separate endpoint shipped in Phase 3.
    """

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    astrologer_id: UUID
    name: str
    portal_slug: UUID
    # Defaults safe for legacy rows pre-dating migration 0003.
    portal_enabled: bool = True
    portal_visibility: dict = {}

    # Convenience counts. Useful for the CRM roster ("Harini · 12 sessions, 3 notes")
    # without an extra round-trip per row.
    chart_session_count: int = 0
    note_count: int = 0
    last_session_at: Optional[datetime] = None

    created_at: datetime
    updated_at: datetime


class ClientList(BaseModel):
    """List response wrapper.

    Pagination + total kept as wrapper so we can add cursor pagination
    later without a breaking change. For v1, we return everything in
    one shot (most astrologers will have <500 clients; offset/limit
    is enough).
    """

    items: list[ClientPublic]
    total: int


# ─── Helpers ──────────────────────────────────────────────────────────


async def _get_owned_or_404(
    client_id: UUID,
    astrologer: CurrentAstrologer,
    db: AsyncSession,
) -> Client:
    """Look up a client and verify the current astrologer owns it.

    Raises 404 if missing OR owned by someone else (don't leak
    existence). Same pattern as chart_sessions router.
    """
    stmt = select(Client).where(
        Client.id == client_id,
        Client.astrologer_id == astrologer.id,
    )
    result = await db.execute(stmt)
    row = result.scalar_one_or_none()
    if row is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"error": "client_not_found"},
        )
    return row


def _client_to_public(
    row: Client,
    chart_session_count: int = 0,
    note_count: int = 0,
    last_session_at: Optional[datetime] = None,
) -> ClientPublic:
    """Build ClientPublic explicitly from a Client SQLAlchemy row.

    2026-06-02 hotfix: was using ClientPublic.model_validate(row) which
    uses Pydantic's from_attributes=True. That triggered 500 errors on
    POST /clients because Pydantic was traversing SQLAlchemy attributes
    in a way that conflicted with our `lazy="raise"` relationship
    setting (any incidental access of row.chart_sessions or row.notes
    raises InvalidRequestError on a freshly-flushed row whose
    relationships haven't been eager-loaded).

    Explicit field mapping avoids the issue entirely — we only read
    scalar columns, never relationships.
    """
    return ClientPublic(
        id=row.id,
        astrologer_id=row.astrologer_id,
        name=row.name,
        phone=row.phone,
        email=row.email,
        gender=row.gender,
        birth_date=row.birth_date,
        birth_time=row.birth_time,
        birth_place_name=row.birth_place_name,
        birth_latitude=row.birth_latitude,
        birth_longitude=row.birth_longitude,
        birth_timezone_offset=row.birth_timezone_offset,
        matching_opt_in=row.matching_opt_in,
        portal_slug=row.portal_slug,
        # getattr with default — legacy rows pre-dating migration 0003
        # serialize cleanly even before the DB migration applies.
        portal_enabled=getattr(row, "portal_enabled", True),
        portal_visibility=getattr(row, "portal_visibility", {}) or {},
        summary=row.summary,
        chart_session_count=chart_session_count,
        note_count=note_count,
        last_session_at=last_session_at,
        created_at=row.created_at,
        updated_at=row.updated_at,
    )


async def _attach_counts(
    rows: list[Client],
    db: AsyncSession,
) -> list[ClientPublic]:
    """Bulk-compute chart_session + note counts for a list of clients.

    Two queries (one per related table) regardless of list size, vs
    N+1 queries if we did this naively per row.
    """
    if not rows:
        return []

    client_ids = [r.id for r in rows]

    # Chart session counts + most-recent updated_at per client
    sess_stmt = (
        select(
            ChartSession.client_id,
            func.count(ChartSession.id).label("cnt"),
            func.max(ChartSession.updated_at).label("last_at"),
        )
        .where(ChartSession.client_id.in_(client_ids))
        .group_by(ChartSession.client_id)
    )
    sess_rows = (await db.execute(sess_stmt)).all()
    sess_map: dict[UUID, tuple[int, datetime]] = {
        r.client_id: (r.cnt, r.last_at) for r in sess_rows
    }

    # Note counts per client
    note_stmt = (
        select(
            ClientNote.client_id,
            func.count(ClientNote.id).label("cnt"),
        )
        .where(ClientNote.client_id.in_(client_ids))
        .group_by(ClientNote.client_id)
    )
    note_rows = (await db.execute(note_stmt)).all()
    note_map: dict[UUID, int] = {r.client_id: r.cnt for r in note_rows}

    out: list[ClientPublic] = []
    for r in rows:
        sess_cnt, last_at = sess_map.get(r.id, (0, None))
        out.append(
            _client_to_public(
                r,
                chart_session_count=sess_cnt,
                note_count=note_map.get(r.id, 0),
                last_session_at=last_at,
            )
        )
    return out


# ─── Routes ───────────────────────────────────────────────────────────


@router.get("", response_model=ClientList)
async def list_clients(
    astrologer: CurrentAstrologer,
    limit: int = 100,
    offset: int = 0,
    db: AsyncSession = Depends(get_db),
) -> ClientList:
    """List the current astrologer's clients, most-recently-touched first.

    C4 fix (2026-06-02): added pagination. Previous behavior was "send
    the entire roster as one response" — fine for ten clients, ugly for
    five thousand. Default limit 100 keeps the existing CRM-home behavior
    intact for typical astrologers; offset/limit query params let UI
    paginate. `total` in the response is the FULL count for the
    astrologer (not the page-size count) so pagers can render
    "Showing 1-100 of 437".

    Bounds:
      limit:  1-500 (caps at 500 even if larger requested — prevents
              denial-of-wallet by a malicious request asking for limit=999999)
      offset: ≥0
    """
    limit = max(1, min(int(limit), 500))
    offset = max(0, int(offset))

    # Total count for pagination header
    total_stmt = (
        select(func.count(Client.id))
        .where(Client.astrologer_id == astrologer.id)
    )
    total = int((await db.execute(total_stmt)).scalar() or 0)

    stmt = (
        select(Client)
        .where(Client.astrologer_id == astrologer.id)
        .order_by(Client.updated_at.desc())
        .offset(offset)
        .limit(limit)
    )
    result = await db.execute(stmt)
    rows = list(result.scalars().all())
    enriched = await _attach_counts(rows, db)
    return ClientList(items=enriched, total=total)


@router.post(
    "",
    response_model=ClientPublic,
    status_code=status.HTTP_201_CREATED,
)
async def create_client(
    payload: ClientCreate,
    astrologer: CurrentAstrologer,
    db: AsyncSession = Depends(get_db),
) -> ClientPublic:
    """Create a new client owned by the current astrologer.

    Does NOT compute the chart — that's a separate flow. Frontend
    typically does:
      1. POST /clients with name + birth details → creates client row
      2. POST /astrologer/workspace with birth details → computes chart
      3. POST /chart-sessions with client_id + workspace_data → persists
    See the CRM Add Client modal in Slice 3 for the orchestration.
    """
    # S2 hardening (2026-06-02): catch-log-rollback-rethrow with NO
    # leaky exception details in the response body. The verbose debug
    # variant was added to chase down the portal_slug bug (fixed
    # 5d42052) — root cause now known, removing the leak. Internals
    # still log to Railway with full stack trace + request_id so we
    # can debug from logs without exposing schema/SQL hints to clients.
    try:
        row = Client(
            astrologer_id=astrologer.id,
            **payload.model_dump(exclude_unset=True),
        )
        db.add(row)
        await db.flush()  # populate id + portal_slug + created_at
        # Newly created → zero sessions / notes. Use explicit
        # constructor (not model_validate) — see _client_to_public
        # docstring for why.
        return _client_to_public(row, chart_session_count=0, note_count=0)
    except HTTPException:
        raise
    except Exception:
        # Log full stack trace to Railway logs (carries request_id
        # via the RequestIdMiddleware access log line; correlate by
        # X-Request-ID header returned to the client).
        _log.exception(
            "create_client_failed astrologer_id=%s payload_keys=%s",
            astrologer.id,
            list(payload.model_dump(exclude_unset=True).keys()),
        )
        # Rollback so the session can be reused for the next request.
        try:
            await db.rollback()
        except Exception:
            pass
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={"error": "create_client_failed"},
        )


@router.get("/{client_id}", response_model=ClientPublic)
async def get_client(
    client_id: UUID,
    astrologer: CurrentAstrologer,
    db: AsyncSession = Depends(get_db),
) -> ClientPublic:
    """Read one client by id (must be owned by current astrologer)."""
    row = await _get_owned_or_404(client_id, astrologer, db)
    enriched = await _attach_counts([row], db)
    return enriched[0]


@router.patch("/{client_id}", response_model=ClientPublic)
async def update_client(
    client_id: UUID,
    payload: ClientUpdate,
    astrologer: CurrentAstrologer,
    db: AsyncSession = Depends(get_db),
) -> ClientPublic:
    """Update one or more fields. Unset fields are not touched.

    NOTE: birth fields are mutable here. If the astrologer rectifies
    the birth time, this updates them. BUT the chart_sessions rows
    have their own birth-field snapshots (see ChartSession model
    docstring) — those don't auto-update. That's by design: each
    chart_session captures the input used when it was created, so
    rectification creates a new chart_session, not mutates old ones.
    The frontend (in Slice 3+) presents rectification as
    "Recompute chart" → which POSTs a new /chart-sessions row, not
    a PATCH of an existing one.
    """
    row = await _get_owned_or_404(client_id, astrologer, db)
    changes = payload.model_dump(exclude_unset=True)
    for field, value in changes.items():
        setattr(row, field, value)
    await db.flush()
    enriched = await _attach_counts([row], db)
    return enriched[0]


class ClientWithChartCreate(ClientCreate):
    """Inputs for the transactional add-client-with-chart endpoint."""

    # The chart engine needs ISO date + 24h time. Frontend converts
    # before posting (handles AM/PM + DD/MM/YYYY → YYYY-MM-DD itself).
    chart_iso_date: str = Field(..., min_length=10, max_length=10)
    chart_time_24h: str = Field(..., min_length=4, max_length=8)
    # AM/PM is preserved so chart_session.birth_ampm gets populated for
    # the UI to display the original format the astrologer entered.
    chart_ampm: str = Field("AM", max_length=2)


class ClientWithChartResponse(BaseModel):
    """Combined response — both rows created in one transaction."""

    client: ClientPublic
    chart_session_id: UUID


@router.post(
    "/with-chart",
    response_model=ClientWithChartResponse,
    status_code=status.HTTP_201_CREATED,
)
async def create_client_with_chart(
    payload: ClientWithChartCreate,
    astrologer: CurrentAstrologer,
    db: AsyncSession = Depends(get_db),
) -> ClientWithChartResponse:
    """C1 fix (2026-06-02): single transactional endpoint that creates
    the client row, computes the chart, AND persists the chart_session
    — atomically. Eliminates the orphan-row class of bugs.

    Previous flow (frontend orchestrated):
      1. POST /clients               (could succeed)
      2. POST /astrologer/workspace  (could fail → orphan client)
      3. POST /chart-sessions        (could fail → orphan client)
    User-visible symptom: duplicate "manyue" rows in the CRM roster
    when step 2 failed and the user re-tried the whole flow.

    New flow: everything happens inside one DB session. If chart
    compute or chart_session insert fails, the client INSERT rolls
    back via the get_db() commit-on-clean-exit semantics. No orphans.

    Frontend AddClientModal is updated in Wave 4 to call this endpoint
    instead of the 3-step sequence.
    """
    # Lazy import — the chart engine is heavy (swisseph + ephemeris
    # files) and we don't want to pay that cost at module load.
    from app.services.chart_engine import (
        generate_chart, calculate_dashas, get_current_dasha,
        calculate_antardashas, get_current_antardasha,
        calculate_pratyantardashas, get_current_pratyantardasha,
        get_ruling_planets, get_all_house_significators,
    )
    from app.services.chart_formatter import format_chart_for_frontend
    from app.services.chart_pipeline import _resolve_rp_triple, build_rp_meta
    from app.services.timezone_utils import resolve_birth_offset
    # P2-13 fix (deep-scan-2): dropped unused imports of
    # get_planet_telugu / get_sign_telugu / get_nakshatra_telugu /
    # get_house_telugu — they were brought in by reflex and never used
    # (the chart formatter already handles Telugu names).
    from app.db.models import ChartSession
    import swisseph as _swe

    try:
        # ── Step 1: insert client row (NOT flushed yet — bound to txn) ──
        client_fields = payload.model_dump(
            exclude={"chart_iso_date", "chart_time_24h", "chart_ampm"},
            exclude_unset=True,
        )
        client_row = Client(
            astrologer_id=astrologer.id,
            **client_fields,
        )
        db.add(client_row)
        await db.flush()  # populates client_row.id + portal_slug

        # ── Step 2: compute the chart inline (no second HTTP hop) ──
        if (
            payload.birth_latitude is None
            or payload.birth_longitude is None
        ):
            raise HTTPException(
                status_code=400,
                detail={"error": "missing_birth_coordinates"},
            )
        tz_offset, _tz_name = resolve_birth_offset(
            payload.birth_latitude,
            payload.birth_longitude,
            payload.chart_iso_date,
            payload.chart_time_24h,
            fallback_offset=payload.birth_timezone_offset or 5.5,
        )
        _swe.set_sid_mode(_swe.SIDM_KRISHNAMURTI_VP291)
        chart = generate_chart(
            payload.chart_iso_date,
            payload.chart_time_24h,
            payload.birth_latitude,
            payload.birth_longitude,
            tz_offset,
        )
        moon_longitude = chart["planets"]["Moon"]["longitude"]
        dashas = calculate_dashas(
            payload.chart_iso_date, payload.chart_time_24h,
            moon_longitude, tz_offset,
        )
        current_md = get_current_dasha(dashas)
        antardashas = calculate_antardashas(current_md)
        current_ad = get_current_antardasha(antardashas)
        pratyantardashas = calculate_pratyantardashas(current_ad)
        current_pad = get_current_pratyantardasha(pratyantardashas)
        all_significators = get_all_house_significators(
            chart["planets"], chart["cusps"]
        )
        rp_lat, rp_lon, rp_tz, rp_source = _resolve_rp_triple(
            natal_lat=payload.birth_latitude,
            natal_lon=payload.birth_longitude,
            natal_tz=tz_offset,
            live_lat=None, live_lon=None, live_tz=None,
        )
        ruling_planets = get_ruling_planets(rp_lat, rp_lon, rp_tz)
        rp_meta = build_rp_meta(rp_lat, rp_lon, rp_tz, source=rp_source)
        formatted = format_chart_for_frontend(chart)

        # Build a workspace_data dict matching what /astrologer/workspace
        # returns — keep the shape compatible so downstream UI doesn't
        # care which endpoint produced it.
        workspace_data: dict[str, Any] = {
            "name": payload.name,
            "date": payload.chart_iso_date,
            "time": payload.chart_time_24h,
            "latitude": payload.birth_latitude,
            "longitude": payload.birth_longitude,
            "timezone_offset": tz_offset,
            "gender": payload.gender or "",
            "planets": formatted["planets"],
            "cusps": formatted["cusps"],
            "current_dasha": current_md,
            "current_antardasha": current_ad,
            "current_pratyantardasha": current_pad,
            "dashas": dashas,
            "all_significators": all_significators,
            "ruling_planets": ruling_planets,
            "rp_meta": rp_meta,
        }

        # ── Step 3: persist chart_session bound to the new client ──
        session_row = ChartSession(
            astrologer_id=astrologer.id,
            client_id=client_row.id,
            name=payload.name,
            birth_name=payload.name,
            birth_date=payload.birth_date,
            birth_time=payload.birth_time,
            birth_ampm=payload.chart_ampm,
            birth_place_name=payload.birth_place_name,
            birth_latitude=payload.birth_latitude,
            birth_longitude=payload.birth_longitude,
            birth_timezone_offset=tz_offset,
            birth_gender=payload.gender,
            workspace_data=workspace_data,
        )
        db.add(session_row)
        await db.flush()  # populates session_row.id

        # All three operations succeeded — get_db()'s commit-on-clean-
        # exit will commit. Returning the response triggers that path.
        public = _client_to_public(
            client_row, chart_session_count=1, note_count=0
        )
        return ClientWithChartResponse(
            client=public, chart_session_id=session_row.id
        )

    except HTTPException:
        raise
    except Exception:
        _log.exception(
            "create_client_with_chart_failed astrologer_id=%s",
            astrologer.id,
        )
        # get_db() session dep auto-rollbacks on exception — no need
        # to call rollback explicitly here.
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={"error": "create_client_with_chart_failed"},
        )


@router.delete("/{client_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_client(
    client_id: UUID,
    astrologer: CurrentAstrologer,
    db: AsyncSession = Depends(get_db),
) -> None:
    """Delete a client. CASCADES to chart_sessions + client_notes via
    the FK ON DELETE CASCADE we set up in the initial migration.

    Idempotent — 404 if it doesn't exist (or isn't yours).

    WARNING: This is destructive. The frontend should confirm before
    calling (\"Delete client + N chart sessions + M notes — are you
    sure?\"). No soft-delete in v1; we'll add a `deleted_at` column
    + tombstone behavior if astrologers ask for "undelete."
    """
    row = await _get_owned_or_404(client_id, astrologer, db)
    await db.delete(row)
