"""initial schema — 7 tables for Phase 1 auth+DB foundation

Revision ID: 20260601_0001
Revises:
Create Date: 2026-06-01

Phase 1 (2026-06-01) initial DB schema per:
  - ADR-001 (SQLAlchemy 2.0 + Alembic)
  - launch-tracker-2026-09-09.md (P0 #2, #3)
  - pricing-payment-business-spec.md (subscription model)
  - client-portal-spec.md (clients + client_notes + portal_slug)
  - matching-network-spec.md (matching_opt_in column)

Tables created:
  1. astrologers       — paying users, bridged to Supabase Auth by sub
  2. clients           — astrologer's CRM-like client roster
  3. chart_sessions    — saved charts (replaces localStorage)
  4. client_notes      — astrologer's per-client timeline notes
  5. subscriptions     — billing state (plan, status, AI quota, Razorpay)
  6. usage_events      — append-only billable + analytics log
  7. audit_log         — security + compliance trail

Hand-written (not autogenerated) because we don't have a live DB to
diff against yet. When the user provisions Railway Postgres + sets
DATABASE_URL, `alembic upgrade head` applies this in one shot.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Alembic identifiers
revision: str = "20260601_0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ──────────────────────────────────────────────────────────────────
    # Extensions
    # ──────────────────────────────────────────────────────────────────
    # pgcrypto provides gen_random_uuid() which we use as the default
    # for every UUID PK. Postgres 13+ has it built-in but Railway may
    # run older versions — enable the extension to be safe.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ──────────────────────────────────────────────────────────────────
    # 1. astrologers
    # ──────────────────────────────────────────────────────────────────
    op.create_table(
        "astrologers",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        sa.Column("supabase_user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("display_name", sa.String(120)),
        sa.Column("bio", sa.Text()),
        sa.Column("photo_url", sa.String(2048)),
        sa.Column("phone", sa.String(20)),
        sa.Column("years_practicing", sa.Integer()),
        sa.Column(
            "is_verified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "default_language",
            sa.String(10),
            server_default="en",
            nullable=False,
        ),
        sa.Column("onboarded_at", sa.Date()),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.UniqueConstraint("supabase_user_id", name="uq_astrologers_supabase_user_id"),
        sa.UniqueConstraint("email", name="uq_astrologers_email"),
    )
    op.create_index(
        "ix_astrologers_supabase_user_id",
        "astrologers",
        ["supabase_user_id"],
    )
    op.create_index("ix_astrologers_email", "astrologers", ["email"])

    # ──────────────────────────────────────────────────────────────────
    # 2. clients
    # ──────────────────────────────────────────────────────────────────
    op.create_table(
        "clients",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        sa.Column(
            "astrologer_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("astrologers.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("phone", sa.String(20)),
        sa.Column("email", sa.String(320)),
        sa.Column("gender", sa.String(10)),
        sa.Column("birth_date", sa.String(10)),
        sa.Column("birth_time", sa.String(8)),
        sa.Column("birth_place_name", sa.String(500)),
        sa.Column("birth_latitude", sa.Float()),
        sa.Column("birth_longitude", sa.Float()),
        sa.Column("birth_timezone_offset", sa.Float()),
        sa.Column(
            "matching_opt_in",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "portal_slug",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            unique=True,
        ),
        sa.Column("summary", sa.Text()),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_clients_astrologer_id_created_at",
        "clients",
        ["astrologer_id", "created_at"],
    )
    op.create_index("ix_clients_portal_slug", "clients", ["portal_slug"])
    # Partial index for Phase M matching scans — keeps it tiny since most
    # clients won't opt in.
    op.create_index(
        "ix_clients_matching_opt_in_true",
        "clients",
        ["gender", "birth_date"],
        postgresql_where=sa.text("matching_opt_in = true"),
    )

    # ──────────────────────────────────────────────────────────────────
    # 3. chart_sessions
    # ──────────────────────────────────────────────────────────────────
    op.create_table(
        "chart_sessions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        sa.Column(
            "astrologer_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("astrologers.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "client_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("clients.id", ondelete="CASCADE"),
        ),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("birth_name", sa.String(200)),
        sa.Column("birth_date", sa.String(10)),
        sa.Column("birth_time", sa.String(8)),
        sa.Column("birth_ampm", sa.String(2)),
        sa.Column("birth_place_name", sa.String(500)),
        sa.Column("birth_latitude", sa.Float()),
        sa.Column("birth_longitude", sa.Float()),
        sa.Column("birth_timezone_offset", sa.Float()),
        sa.Column("birth_gender", sa.String(10)),
        sa.Column("chart_data", postgresql.JSONB()),
        sa.Column("workspace_data", postgresql.JSONB()),
        sa.Column("analysis_messages", postgresql.JSONB()),
        sa.Column("ui_state", postgresql.JSONB()),
        sa.Column("session_notes", sa.Text()),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_chart_sessions_astrologer_id_updated_at",
        "chart_sessions",
        ["astrologer_id", "updated_at"],
    )
    op.create_index(
        "ix_chart_sessions_client_id_created_at",
        "chart_sessions",
        ["client_id", "created_at"],
    )

    # ──────────────────────────────────────────────────────────────────
    # 4. client_notes
    # ──────────────────────────────────────────────────────────────────
    op.create_table(
        "client_notes",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        sa.Column(
            "client_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("clients.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("language", sa.String(10), server_default="en", nullable=False),
        sa.Column(
            "note_type",
            sa.String(40),
            server_default="reading",
            nullable=False,
        ),
        sa.Column(
            "is_private",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column("expected_resolution_date", sa.Date()),
        sa.Column("resolved", sa.Boolean()),
        sa.Column("resolved_at", sa.Date()),
        sa.Column("resolution_note", sa.Text()),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_client_notes_client_id_created_at",
        "client_notes",
        ["client_id", "created_at"],
    )
    op.create_index(
        "ix_client_notes_portal_visible",
        "client_notes",
        ["client_id", "created_at"],
        postgresql_where=sa.text("is_private = false"),
    )

    # ──────────────────────────────────────────────────────────────────
    # 5. subscriptions
    # ──────────────────────────────────────────────────────────────────
    op.create_table(
        "subscriptions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        sa.Column(
            "astrologer_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("astrologers.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("plan", sa.String(40), nullable=False),
        sa.Column("status", sa.String(40), nullable=False),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True)),
        sa.Column("current_period_start", sa.DateTime(timezone=True)),
        sa.Column("current_period_end", sa.DateTime(timezone=True)),
        sa.Column("canceled_at", sa.DateTime(timezone=True)),
        sa.Column(
            "ai_questions_included_per_period",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "ai_questions_used_this_period",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "topup_credits",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("razorpay_customer_id", sa.String(120)),
        sa.Column("razorpay_subscription_id", sa.String(120)),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.UniqueConstraint(
            "razorpay_subscription_id",
            name="uq_subscriptions_razorpay_subscription_id",
        ),
    )
    op.create_index(
        "ix_subscriptions_astrologer_id_status",
        "subscriptions",
        ["astrologer_id", "status"],
    )

    # ──────────────────────────────────────────────────────────────────
    # 6. usage_events
    # ──────────────────────────────────────────────────────────────────
    op.create_table(
        "usage_events",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        sa.Column(
            "astrologer_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("astrologers.id", ondelete="SET NULL"),
        ),
        sa.Column(
            "client_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("clients.id", ondelete="SET NULL"),
        ),
        sa.Column(
            "chart_session_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("chart_sessions.id", ondelete="SET NULL"),
        ),
        sa.Column("event_type", sa.String(80), nullable=False),
        sa.Column("payload", postgresql.JSONB()),
        sa.Column("cost_paise", sa.Integer()),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_usage_events_astrologer_created",
        "usage_events",
        ["astrologer_id", "created_at"],
    )
    op.create_index(
        "ix_usage_events_type_created",
        "usage_events",
        ["event_type", "created_at"],
    )

    # ──────────────────────────────────────────────────────────────────
    # 7. audit_log
    # ──────────────────────────────────────────────────────────────────
    op.create_table(
        "audit_log",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        sa.Column(
            "astrologer_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("astrologers.id", ondelete="SET NULL"),
        ),
        sa.Column("action", sa.String(80), nullable=False),
        sa.Column("target_type", sa.String(40)),
        sa.Column("target_id", postgresql.UUID(as_uuid=True)),
        sa.Column("ip_hash", sa.String(64)),
        sa.Column("user_agent", sa.String(512)),
        sa.Column("request_id", sa.String(40)),
        sa.Column("detail", postgresql.JSONB()),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_audit_log_astrologer_created",
        "audit_log",
        ["astrologer_id", "created_at"],
    )
    op.create_index(
        "ix_audit_log_action_created",
        "audit_log",
        ["action", "created_at"],
    )
    op.create_index(
        "ix_audit_log_target",
        "audit_log",
        ["target_type", "target_id"],
    )


def downgrade() -> None:
    # Drop in reverse order so FKs unwind cleanly.
    op.drop_index("ix_audit_log_target", table_name="audit_log")
    op.drop_index("ix_audit_log_action_created", table_name="audit_log")
    op.drop_index("ix_audit_log_astrologer_created", table_name="audit_log")
    op.drop_table("audit_log")

    op.drop_index("ix_usage_events_type_created", table_name="usage_events")
    op.drop_index("ix_usage_events_astrologer_created", table_name="usage_events")
    op.drop_table("usage_events")

    op.drop_index(
        "ix_subscriptions_astrologer_id_status",
        table_name="subscriptions",
    )
    op.drop_table("subscriptions")

    op.drop_index("ix_client_notes_portal_visible", table_name="client_notes")
    op.drop_index(
        "ix_client_notes_client_id_created_at",
        table_name="client_notes",
    )
    op.drop_table("client_notes")

    op.drop_index(
        "ix_chart_sessions_client_id_created_at",
        table_name="chart_sessions",
    )
    op.drop_index(
        "ix_chart_sessions_astrologer_id_updated_at",
        table_name="chart_sessions",
    )
    op.drop_table("chart_sessions")

    op.drop_index("ix_clients_matching_opt_in_true", table_name="clients")
    op.drop_index("ix_clients_portal_slug", table_name="clients")
    op.drop_index("ix_clients_astrologer_id_created_at", table_name="clients")
    op.drop_table("clients")

    op.drop_index("ix_astrologers_email", table_name="astrologers")
    op.drop_index(
        "ix_astrologers_supabase_user_id",
        table_name="astrologers",
    )
    op.drop_table("astrologers")
    # pgcrypto extension intentionally left in place — other migrations
    # may depend on it.
