"""v2_phase1_core_schema

Revision ID: 9bc866d2a214
Revises: 
Create Date: 2026-04-16 22:37:15.463203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '9bc866d2a214'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=16), server_default=sa.text("'consumer'"), nullable=False),
    sa.Column('tier', sa.String(length=24), server_default=sa.text("'free'"), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=64), nullable=True),
    sa.Column('locale', sa.String(length=16), server_default=sa.text("'en'"), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('consumer','astrologer','admin')", name='profiles_role_check'),
    sa.CheckConstraint("tier IN ('free','consumer_pro','astrologer_pro','team')", name='profiles_tier_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_table('stripe_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=16), server_default=sa.text("'solo'"), nullable=False),
    sa.Column('seat_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("plan IN ('solo','team','enterprise')", name='orgs_plan_check'),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('tier', sa.String(length=24), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_id', sa.String(length=64), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_daily',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('ai_questions', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('charts_generated', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('pdf_exports', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('muhurtha_searches', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('horary_queries', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'day')
    )
    op.create_table('clients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('astrologer_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('preferred_name', sa.Text(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('birth_dt_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('birth_dt_local_str', sa.String(length=32), nullable=False),
    sa.Column('birth_timezone', sa.String(length=48), nullable=False),
    sa.Column('birth_lat', sa.Float(), nullable=False),
    sa.Column('birth_lon', sa.Float(), nullable=False),
    sa.Column('birth_place', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default=sa.text('ARRAY[]::text[]'), nullable=False),
    sa.Column('notes_private', sa.Text(), nullable=True),
    sa.Column('chart_cache', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cache_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('relation_to_astrologer', sa.String(length=32), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("gender IS NULL OR gender IN ('male','female','other','unspecified')", name='clients_gender_check'),
    sa.ForeignKeyConstraint(['astrologer_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clients_astrologer_id', 'clients', ['astrologer_id'], unique=False)
    op.create_index('ix_clients_fulltext', 'clients', [sa.literal_column("to_tsvector('simple', coalesce(full_name,'') || ' ' || coalesce(phone,'') || ' ' || coalesce(email,'') || ' ' || coalesce(birth_place,''))")], unique=False, postgresql_using='gin')
    op.create_index('ix_clients_org_id', 'clients', ['org_id'], unique=False)
    op.create_index('ix_clients_tags_gin', 'clients', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('org_members',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner','admin','astrologer','assistant')", name='org_members_role_check'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id', 'user_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('astrologer_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('session_type', sa.String(length=24), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'scheduled'"), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('horary_number', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('summary_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fee_charged', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('is_paid', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("session_type IN ('natal','horary','transit','muhurtha','marriage','followup','walkin')", name='sessions_type_check'),
    sa.CheckConstraint("status IN ('scheduled','in_progress','completed','cancelled','no_show')", name='sessions_status_check'),
    sa.CheckConstraint('horary_number IS NULL OR (horary_number BETWEEN 1 AND 249)', name='sessions_horary_range'),
    sa.ForeignKeyConstraint(['astrologer_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_astrologer_id_scheduled', 'sessions', ['astrologer_id', 'scheduled_at'], unique=False)
    op.create_index('ix_sessions_client_id_scheduled', 'sessions', ['client_id', 'scheduled_at'], unique=False)
    op.create_index('ix_sessions_embedding_hnsw', 'sessions', ['summary_embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'summary_embedding': 'vector_cosine_ops'})
    op.create_index('ix_sessions_status', 'sessions', ['status'], unique=False)
    op.create_table('ai_threads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('astrologer_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['astrologer_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_threads_astrologer_updated', 'ai_threads', ['astrologer_id', 'last_message_at'], unique=False)
    op.create_index('ix_threads_client_id', 'ai_threads', ['client_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('astrologer_id', sa.UUID(), nullable=False),
    sa.Column('prediction_text', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=24), nullable=False),
    sa.Column('target_window_start', sa.Date(), nullable=True),
    sa.Column('target_window_end', sa.Date(), nullable=True),
    sa.Column('kp_basis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outcome', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('outcome_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("domain IN ('career','marriage','health','finance','education','travel','foreign','property','children','litigation','spiritual','other')", name='predictions_domain_check'),
    sa.CheckConstraint("outcome IN ('pending','correct','partial','wrong','unverifiable')", name='predictions_outcome_check'),
    sa.ForeignKeyConstraint(['astrologer_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictions_astrologer_outcome', 'predictions', ['astrologer_id', 'outcome'], unique=False)
    op.create_index('ix_predictions_client_id', 'predictions', ['client_id'], unique=False)
    op.create_index('ix_predictions_pending_window', 'predictions', ['target_window_start', 'target_window_end'], unique=False, postgresql_where=sa.text("outcome = 'pending'"))
    op.create_table('ai_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user','assistant','system','tool')", name='ai_messages_role_check'),
    sa.ForeignKeyConstraint(['thread_id'], ['ai_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_messages_thread_created', 'ai_messages', ['thread_id', 'created_at'], unique=False)
    op.create_table('followups',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('prediction_id', sa.UUID(), nullable=True),
    sa.Column('astrologer_id', sa.UUID(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=24), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('manual','prediction_window','dasha_transition','session_ended','system')", name='followups_source_check'),
    sa.ForeignKeyConstraint(['astrologer_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_followups_astrologer_due_open', 'followups', ['astrologer_id', 'due_at'], unique=False, postgresql_where=sa.text('completed_at IS NULL AND dismissed_at IS NULL'))
    # ### end Alembic commands ###

    # ═══════════════════════════════════════════════════════════════
    # POST-AUTOGEN: Supabase-specific additions
    # ═══════════════════════════════════════════════════════════════

    # 1. Foreign key: profiles.id → auth.users(id) ON DELETE CASCADE
    #    (not in ORM because auth schema is Supabase-managed)
    op.execute(
        """
        ALTER TABLE public.profiles
        ADD CONSTRAINT profiles_id_fkey
        FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
        """
    )

    # 2. Trigger: when a new auth.users row is inserted (signup),
    #    auto-create a public.profiles row with defaults.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION public.handle_new_user()
        RETURNS trigger
        LANGUAGE plpgsql
        SECURITY DEFINER
        SET search_path = public
        AS $$
        BEGIN
          INSERT INTO public.profiles (id, email, full_name, role, tier)
          VALUES (
            NEW.id,
            NEW.email,
            COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.email),
            COALESCE(NEW.raw_user_meta_data->>'role', 'consumer'),
            'free'
          );
          RETURN NEW;
        END;
        $$;
        """
    )
    op.execute("DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;")
    op.execute(
        """
        CREATE TRIGGER on_auth_user_created
          AFTER INSERT ON auth.users
          FOR EACH ROW
          EXECUTE FUNCTION public.handle_new_user();
        """
    )

    # 3. Enable Row-Level Security on every tenant-scoped table
    rls_tables = [
        "profiles",
        "organizations",
        "org_members",
        "clients",
        "sessions",
        "predictions",
        "followups",
        "ai_threads",
        "ai_messages",
        "usage_daily",
        "subscriptions",
    ]
    for t in rls_tables:
        op.execute(f"ALTER TABLE public.{t} ENABLE ROW LEVEL SECURITY;")

    # stripe_events — read by service role only, no RLS needed (deny-all)
    op.execute("ALTER TABLE public.stripe_events ENABLE ROW LEVEL SECURITY;")

    # 4. RLS Policies — one statement per execute (asyncpg limitation)
    policies = [
        # profiles: user sees own profile
        "CREATE POLICY profiles_self ON public.profiles "
        "FOR ALL USING (id = auth.uid()) WITH CHECK (id = auth.uid());",
        # clients: owner (astrologer) full access + org-mate read
        "CREATE POLICY clients_owner ON public.clients "
        "FOR ALL USING (astrologer_id = auth.uid()) WITH CHECK (astrologer_id = auth.uid());",
        "CREATE POLICY clients_org_read ON public.clients FOR SELECT "
        "USING (org_id IS NOT NULL AND "
        "org_id IN (SELECT org_id FROM public.org_members WHERE user_id = auth.uid()));",
        # sessions
        "CREATE POLICY sessions_owner ON public.sessions "
        "FOR ALL USING (astrologer_id = auth.uid()) WITH CHECK (astrologer_id = auth.uid());",
        "CREATE POLICY sessions_org_read ON public.sessions FOR SELECT "
        "USING (org_id IS NOT NULL AND "
        "org_id IN (SELECT org_id FROM public.org_members WHERE user_id = auth.uid()));",
        # predictions
        "CREATE POLICY predictions_owner ON public.predictions "
        "FOR ALL USING (astrologer_id = auth.uid()) WITH CHECK (astrologer_id = auth.uid());",
        # followups
        "CREATE POLICY followups_owner ON public.followups "
        "FOR ALL USING (astrologer_id = auth.uid()) WITH CHECK (astrologer_id = auth.uid());",
        # ai_threads
        "CREATE POLICY ai_threads_owner ON public.ai_threads "
        "FOR ALL USING (astrologer_id = auth.uid()) WITH CHECK (astrologer_id = auth.uid());",
        # ai_messages via thread
        "CREATE POLICY ai_messages_via_thread ON public.ai_messages FOR ALL "
        "USING (thread_id IN (SELECT id FROM public.ai_threads WHERE astrologer_id = auth.uid())) "
        "WITH CHECK (thread_id IN (SELECT id FROM public.ai_threads WHERE astrologer_id = auth.uid()));",
        # usage_daily self
        "CREATE POLICY usage_self ON public.usage_daily "
        "FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());",
        # subscriptions self-read
        "CREATE POLICY subscriptions_self_read ON public.subscriptions FOR SELECT "
        "USING (user_id = auth.uid());",
        # organizations
        "CREATE POLICY orgs_owner ON public.organizations "
        "FOR ALL USING (owner_id = auth.uid()) WITH CHECK (owner_id = auth.uid());",
        "CREATE POLICY orgs_member_read ON public.organizations FOR SELECT "
        "USING (id IN (SELECT org_id FROM public.org_members WHERE user_id = auth.uid()));",
        # org_members
        "CREATE POLICY org_members_self ON public.org_members FOR SELECT "
        "USING (org_id IN (SELECT org_id FROM public.org_members WHERE user_id = auth.uid()));",
        "CREATE POLICY org_members_owner_write ON public.org_members FOR ALL "
        "USING (org_id IN (SELECT id FROM public.organizations WHERE owner_id = auth.uid())) "
        "WITH CHECK (org_id IN (SELECT id FROM public.organizations WHERE owner_id = auth.uid()));",
    ]
    for policy_sql in policies:
        op.execute(policy_sql)
    # NOTE: stripe_events has RLS enabled with zero policies = full deny
    # for authenticated users. Only service_role can read/write it.


def downgrade() -> None:
    """Downgrade schema."""
    # Drop trigger + function first
    op.execute("DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;")
    op.execute("DROP FUNCTION IF EXISTS public.handle_new_user();")
    op.execute("ALTER TABLE IF EXISTS public.profiles DROP CONSTRAINT IF EXISTS profiles_id_fkey;")
    # ### commands auto generated by Alembic - please adjust! ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_followups_astrologer_due_open', table_name='followups', postgresql_where=sa.text('completed_at IS NULL AND dismissed_at IS NULL'))
    op.drop_table('followups')
    op.drop_index('ix_ai_messages_thread_created', table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index('ix_predictions_pending_window', table_name='predictions', postgresql_where=sa.text("outcome = 'pending'"))
    op.drop_index('ix_predictions_client_id', table_name='predictions')
    op.drop_index('ix_predictions_astrologer_outcome', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_threads_client_id', table_name='ai_threads')
    op.drop_index('ix_threads_astrologer_updated', table_name='ai_threads')
    op.drop_table('ai_threads')
    op.drop_index('ix_sessions_status', table_name='sessions')
    op.drop_index('ix_sessions_embedding_hnsw', table_name='sessions', postgresql_using='hnsw', postgresql_ops={'summary_embedding': 'vector_cosine_ops'})
    op.drop_index('ix_sessions_client_id_scheduled', table_name='sessions')
    op.drop_index('ix_sessions_astrologer_id_scheduled', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('org_members')
    op.drop_index('ix_clients_tags_gin', table_name='clients', postgresql_using='gin')
    op.drop_index('ix_clients_org_id', table_name='clients')
    op.drop_index('ix_clients_fulltext', table_name='clients', postgresql_using='gin')
    op.drop_index('ix_clients_astrologer_id', table_name='clients')
    op.drop_table('clients')
    op.drop_table('usage_daily')
    op.drop_table('subscriptions')
    op.drop_table('organizations')
    op.drop_table('stripe_events')
    op.drop_table('profiles')
    # ### end Alembic commands ###
